export const TABLE_RESIZE = 'TABLE_RESIZE';
export const CHANGE_TEXT = 'CHANGE_TEXT';
export const CELL_STYLE_CHANGE = 'CELL_STYLE_CHANGE';
export const APPLY_CELL_STYLES = 'APLY_CELL_STYLES';
export const TABLE_NAME_CHANGE = 'TABLE_NAME_CHANGE';
export const TABLE_OPENED = 'TABLE_OPENED';
